### PR TITLE
redundant code removed.

### PR DESCRIPTION
**Pull request by MayankSingh1993**
removed some of redundant code

### CODE REVIEW

**Comment by MayankSingh1993** [comment]
just removed the redundant code.

**Comment by arshadkazmi42** [comment]
looks good. thank you for working on this

**Comment by arshadkazmi42** [comment]
@MayankSingh1993 have you tested the apk after the changes?

**Comment by MayankSingh1993** [comment]
Yes it was working well.

**Comment by MayankSingh1993** [comment]
Happy to contribute.

**Comment by arshadkazmi42** [comment]
Closing due to inactivity

**Pull request closed without merging**
